version: "3.9"
services:
  service:
    image: airbnd_test_1
    links:
      - "browserless"
    depends_on:
      - "browserless"
    environment:
      REMOTE_DRIVER_HOST: "browserless"
  browserless:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD","curl", "-f", "http://browserless:3000"]
      interval: 10s
      timeout: 5s
      retries: 2
